server:
  port: 8888
management:
  endpoint:
    shutdown:
      enabled: true
      sensitive: false
  endpoints:
    web:
      exposure:
        include: "shutdown"
spring:
  security:
    user:
      name: ${APIUSER:admin}
      password: ${APIPWD:1}

  redis:
    host: ${RedisHost:redis}
    port: 6379
    database: 1
    password:
  # JavaMailSender 邮件发送的配置
  mail:
    host: smtp.139.com
    username: 18759478272@139.com
    password: XXXX
    test-connection: false
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactor
music-api: ${MusicApi:http://jusicMusicApi}
jusic:
  music-expire-time: ${MusicExpireTime:1200000}
  retry-count: ${ReTryCount:1}
  vote-rate: ${VoteRate:0.3}
  default-music-file: 'classpath:music/default-list.txt'#'file:/usr/local/nginx/html/default-list.txt' # ## #
  wy-top-url: ${WyTopUrl:3778678}
  music-json: 'classpath:lizhimusic.json'#'file:/usr/local/nginx/html/lizhimusic.json'##json格式歌曲列表（for禁歌） # #
  music-serve-domain: ${music-api}:3000 #'http://www.alang.run:8888'
  music-serve-domain-qq: ${music-api}:3300 #'http://www.alang.run:3300'
  music-serve-domain-mg: ${music-api}:3400 #'http://www.alang.run:3400'#
  music-serve-domain-kw-xm: ${music-api}:8081 #'http://www.alang.run:8081'#'
  mail-send-from: ${MailFrom:18759478272@139.com}
  mail-send-to: ${MailTo:1040927107@qq.com}
  serverJUrl: ${ServerJUrl:https://sc.ftqq.com/SCU64668T909ada7955daadfb64d5e7652b93fb135dad06e659369.send}
  ip_house: ${IpHouse:3}
  house_size: ${HouseSize:32}
  mini_id: ${MiniId:xxxxx}
  mini_secrect: ${MiniSecrect:yyyyy},
  role_root_password: ${RoleRootPassword:654321}